### ISSUE TITLE
Error Running

### ISSUE THREAD

**Issue by Immortalin** [christopherdumas/atomicdatabase#7]
Python 3.7, Ubuntu 18.04.2
```Python
/virtualenvs/atomicdatabase/lib/python3.6/site-packages/imgui/integrations/__init__.py:15: FutureWarning: 
    Integration layer in imgui.integrations is still in experimental mode.
    Expect mayor changes in future versions. For safety it is recommended
    to use code vendoring for specific integration impementation.

    This subpackage should become stable in 1.0.0 version.

    
  """, FutureWarning
Added ReversePredicate pattern.
Added PredicateContraction pattern.
Added Predicate pattern.
Added SimpleQuery pattern.
Added ReverseSimpleQuery pattern.
Added FindEntitySimpleQuery pattern.
Added FindEntitySimpleQueryContraction pattern.
Traceback (most recent call last):
  File "AtomicDatabase/__main__.py", line 257, in <module>
    run()
  File "AtomicDatabase/__main__.py", line 167, in run
    window, gl_context = impl_pysdl2_init()
  File "AtomicDatabase/__main__.py", line 141, in impl_pysdl2_init
    print("Error: Cannot create OpenGL Context! SDL Error: " + SDL_GetError())
TypeError: must be str, not bytes
```

**Comment by alexispurslane** [comment]
Oh that's fun. What happened here is we have an error reporting an error... It wasn't able to open an SDL window, but when it tried to show the error it got a bytes type which can't be concatenated onto a string.

To solve the original error, you need SDL2: `sudo apt-get install libsdl2-dev libsdl2-2.0`.

**Comment by christopherdumas** [comment]
So probably `apt-get install libsdl2-dev`

**Comment by christopherdumas** [comment]
Also check requirements.txt, you might need a few more packages besides the ones in the pip file in the recent merge. (Or I might be thinking of the new runtime branch I didn't finish...) Ill move them over if there are any but before I get to that you'll need to install those manually. `more_itertools` might be one iirc

**Comment by alexispurslane** [comment]
Also, `test.db.json` in the source directory is a useful example database. It contains some stuff referenced in the wiki, too.

**Comment by Immortalin** [comment]
Okay it seems that my SDL2 installation is borked. Closing this for now.

**Comment by alexispurslane** [comment]
Do you know what's wrong with it? I might be able to help figure it out. I mean, ideally you'd be able to run AD on your system!
